In [2]:
#Pandas

In [3]:
#Series labels each element in the vector

In [4]:
import numpy as np
import pandas as pd

In [5]:
counts = pd.Series([0,2,4,6,8])
counts

0    0
1    2
2    4
3    6
4    8
dtype: int64

In [6]:
counts.values

array([0, 2, 4, 6, 8])

In [7]:
counts.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
zoo = pd.Series([34, 56, 54, 42, 88],
                index = ['bear', 'girraffe', 'panda', 'tiger', 'deer'])
zoo

bear        34
girraffe    56
panda       54
tiger       42
deer        88
dtype: int64

In [9]:
zoo['deer']

np.int64(88)

In [10]:
zoo.name = 'counts'
zoo.index.name = 'animals in this zoo'
zoo

animals in this zoo
bear        34
girraffe    56
panda       54
tiger       42
deer        88
Name: counts, dtype: int64

In [11]:
zoo[zoo > 80]

animals in this zoo
deer    88
Name: counts, dtype: int64

In [12]:
stationary = {'pen':10, 'eraser':5, 'pouch':30, 'stickynote':15}
print(stationary)
S = pd.Series(stationary)
print(S)

print('total:', S.sum())

{'pen': 10, 'eraser': 5, 'pouch': 30, 'stickynote': 15}
pen           10
eraser         5
pouch         30
stickynote    15
dtype: int64
total: 60

In [13]:
#DataFrame bi-dimensional Series with 2 or more Indices

In [14]:
data = {"product": ['fan', 'AirCooler', 'washing machine', 'microwave'],
        'sold': [243, 564, 200, 230],
        'profit' : ['40%', '30%', '28%', '58%'],
        'rating': [4.9, 4.8, 3.5, 2.5]}
print(data)
data = pd.DataFrame(data)
data

{'product': ['fan', 'AirCooler', 'washing machine', 'microwave'], 'sold': [243, 564, 200, 230], 'profit': ['40%', '30%', '28%', '58%'], 'rating': [4.9, 4.8, 3.5, 2.5]}

           product  sold profit  rating
0              fan   243    40%     4.9
1        AirCooler   564    30%     4.8
2  washing machine   200    28%     3.5
3        microwave   230    58%     2.5

In [15]:
data.to_dict()

{'product': {0: 'fan', 1: 'AirCooler', 2: 'washing machine', 3: 'microwave'},
 'sold': {0: 243, 1: 564, 2: 200, 3: 230},
 'profit': {0: '40%', 1: '30%', 2: '28%', 3: '58%'},
 'rating': {0: 4.9, 1: 4.8, 2: 3.5, 3: 2.5}}

In [16]:
pd.DataFrame(data.to_dict())

           product  sold profit  rating
0              fan   243    40%     4.9
1        AirCooler   564    30%     4.8
2  washing machine   200    28%     3.5
3        microwave   230    58%     2.5

In [17]:
D = [{'a':i , 'b':8* i} for i in range(5)]
print(D)
pd.DataFrame(D)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 8}, {'a': 2, 'b': 16}, {'a': 3, 'b': 24}, {'a': 4, 'b': 32}]

   a   b
0  0   0
1  1   8
2  2  16
3  3  24
4  4  32

In [18]:
pd.DataFrame(np.random.randint(1,5),
    columns = ['A', 'B'],
    index = ['aa' , 'bb', 'cc'] )

    A  B
aa  1  1
bb  1  1
cc  1  1

In [19]:
#index object are immutable unline NumPy arrays

In [20]:
rng = np.random.RandomState(15)
ser = pd.Series(rng.randint(0,9,2))
ser

0    8
1    5
dtype: int32

In [21]:
Drng = pd.DataFrame(rng.randint(0,9,(3,4)),
                    columns = ['a', 'b', 'c', 'd'])
Drng

   a  b  c  d
0  5  7  0  7
1  5  6  1  7
2  0  4  7  5

In [22]:
area_id = pd.Series({'bandra':14, 'andheri':485, 'SoBo':456, 'kandivali':657},
                      name = 'area_id')
population = pd.Series({'andheri':4676346, 'bandra':23948, 'SoBo':577837, 'daadar':7465876},
                       name = 'population')
area_id.index.name = 'MUMBAI'
population.index.name = 'MUMBAI population'
print(area_id)
population

MUMBAI
bandra        14
andheri      485
SoBo         456
kandivali    657
Name: area_id, dtype: int64

MUMBAI population
andheri    4676346
bandra       23948
SoBo        577837
daadar     7465876
Name: population, dtype: int64

In [23]:
population / area_id

SoBo         1267.186404
andheri      9641.950515
bandra       1710.571429
daadar               NaN
kandivali            NaN
dtype: float64

In [24]:
E = pd.Series([2,4,6], index = [0,1,2])
O = pd.Series([1,3,5], index = [0,1,2])
print(E)
print(O)
print(E+O)

0    2
1    4
2    6
dtype: int64
0    1
1    3
2    5
dtype: int64
0     3
1     7
2    11
dtype: int64

In [25]:
E = pd.Series([2,4,6], index = [0,1,2])
O = pd.Series([1,3,5], index = [1,2,3])
print(E)
print(O)
print(E+O)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [26]:
E.add(O, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [27]:
#Data Wrangling

In [28]:
data

           product  sold profit  rating
0              fan   243    40%     4.9
1        AirCooler   564    30%     4.8
2  washing machine   200    28%     3.5
3        microwave   230    58%     2.5

In [29]:
df = pd.DataFrame({'product':['fan', 'AirCooler', 'microwave'], 'avg_bill':['230', '400', '210',]})
df

     product avg_bill
0        fan      230
1  AirCooler      400
2  microwave      210

In [30]:
df.merge(data)

     product avg_bill  sold profit  rating
0        fan      230   243    40%     4.9
1  AirCooler      400   564    30%     4.8
2  microwave      210   230    58%     2.5

In [31]:
df2 = pd.DataFrame({'Product':['fan', 'AirCooler',], 'avg_bill': ['230', '400']})
df2
data.merge(df2, right_on='Product', left_on='product')

     product  sold profit  rating    Product avg_bill
0        fan   243    40%     4.9        fan      230
1  AirCooler   564    30%     4.8  AirCooler      400

In [32]:
df3 = pd.DataFrame({'product':['fan', 'AirCooler', 'vaccumcleaner'], 'avg_bill':['230', '400', '50']})
df3.merge(data)
data.merge(df3, how = 'outer')

           product   sold profit  rating avg_bill
0        AirCooler  564.0    30%     4.8      400
1              fan  243.0    40%     4.9      230
2        microwave  230.0    58%     2.5      NaN
3    vaccumcleaner    NaN    NaN     NaN       50
4  washing machine  200.0    28%     3.5      NaN

In [33]:
#overlap

In [35]:
serie_a = pd.Series([2.5, 3.0, np.nan, 2.0, np.nan],
                   index = ['a', 'b', 'c', 'd', 'e'])
serie_b = pd.Series(np.arange(len(serie_a), dtype = np.float64),
                    index = ['a', 'b', 'c', 'd', 'e'])

In [36]:
serie_a

a    2.5
b    3.0
c    NaN
d    2.0
e    NaN
dtype: float64

In [37]:
serie_b

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [38]:
pd.Series(np.where(pd.isnull(serie_a), serie_b, serie_a), index = serie_a.index)

a    2.5
b    3.0
c    2.0
d    2.0
e    4.0
dtype: float64

In [39]:
serie_a.combine_first(serie_b)

a    2.5
b    3.0
c    2.0
d    2.0
e    4.0
dtype: float64